baseURL: 'https://www.ensineumacrianca.com.br/'
languageCode: 'pt-BR'
defaultContentLanguage: 'pt'
title: 'Ensine programação pra uma criança sem saber programar'

permalinks:
  atividades: /atividades/:filename/
  conceitos: /conceitos/:filename/

menu:
  nav:
    - name: "Como?"
      url: /
      weight: 1
    - name: Primeiros passos
      url: /introducao/
      weight: 2
    - name: Roteiro de Atividades
      url: /atividades/
      weight: 3
    - name: Conceitos do Scratch
      url: /conceitos/
      weight: 4
    - name: Aulas Gratuitas (matrículas fechadas)
      url: /turma-code-club-2024/
      weight: 5

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2

build:
  buildStats:
    enable: true
  cachebusters:
  - source: assets/notwatching/hugo_stats\.json
    target: css
  - source: (postcss|tailwind)\.config\.js
    target: css
module:
  mounts:
  - source: assets
    target: assets
  - disableWatch: true
    source: hugo_stats.json
    target: assets/notwatching/hugo_stats.json
