baseURL: 'https://www.ensineumacrianca.com.br/'
languageCode: 'pt-BR'
defaultContentLanguage: 'pt'
title: 'Ensine uma Criança'

params:
  description: 'Um roteiro pra te ajudar a guiar o aprendizado de uma criança em Tecnologia, usando <a target="_blank" href="https://pt.wikipedia.org/wiki/Scratch">Scratch</a>.'
  images:
    - images/web-app-manifest-512x512.png

permalinks:
  atividades: /atividades/:filename/
  conceitos: /conceitos/:filename/

markup:
  goldmark:
    renderer:
      unsafe: true

build:
  buildStats:
    enable: true
  cachebusters:
  - source: assets/notwatching/hugo_stats\.json
    target: css
  - source: (postcss|tailwind)\.config\.js
    target: css

module:
  mounts:
  - source: assets
    target: assets
  - disableWatch: true
    source: hugo_stats.json
    target: assets/notwatching/hugo_stats.json

security:
  exec:
    allow:
      - babel
      - npx
      - tailwindcss
