baseURL: 'https://www.ensineumacrianca.com.br/'
languageCode: 'pt-BR'
defaultContentLanguage: 'pt'
title: 'Ensine programação pra uma criança sem saber programar'
theme: "cupper-hugo-theme"

permalinks:
  material: /material/:filename/
  conceitos: /conceitos/:filename/

params:
  description: Contribua com o futuro de uma criança ensinando lógica de programação de uma forma lúdica.
  homeMetaContent: Contribua com o futuro de uma criança ensinando lógica de programação de uma forma lúdica.
  footer: Ensine uma Criança é um projeto independente e sem ligações com a Raspberry Pi Foundation.
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat: 2, Jan, 2006
  katex: true
  search: true
  hideHeaderLinks: false
  showThemeSwitcher: false
  defaultDarkTheme: false
  moveFooterToHeader: false
  # navTitleText: Cupper Theme
  logoAlt: Logo do projeto Ensine uma Criança

menu:
  nav:
    - name: "Como?"
      url: /
      weight: 1
    - name: Primeiros passos
      url: /material/introducao/
      weight: 2
    - name: Roteiro de Atividades
      url: /material/
      weight: 3
    - name: Conceitos do Scratch
      url: /conceitos/
      weight: 4

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
